version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port=8080", "--hostname-strict=false"]
    ports:
      - "8080:8080"
